---
# tasks file for wordpress
- name: Baixa WordPress 
  get_url: 
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Descompacta o WordPress 
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Atualiza o site Apache padrao
  lineinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/wordpress"
  notify:
  - reinicia apache

  